# Generated by Django 3.2.12 on 2023-02-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('formal_study_hours', models.DurationField()),
                ('informal_study_hours', models.DurationField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
