# Generated by Django 3.2.12 on 2023-02-26 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={},
        ),
    ]
