# Generated by Django 4.2.3 on 2023-07-27 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0002_alter_study_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="study",
            options={"ordering": ["date"]},
        ),
        migrations.AddField(
            model_name="study",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]





