# Generated by Django 4.2.3 on 2023-07-27 15:01
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_study_options_study_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="study",
            options={"ordering": ["date", "user"]},
        ), 
    ]
