# Generated by Django 4.2.3 on 2023-07-29 17:49

from django.db import migrations
from base.models import User, Study

def associate_study_records_with_user(apps, schema_editor):
    study = Study.objects.all()

    try:
        facundo_user = User.objects.get(username='Facundo')
        #facundo_user = Study.objects.get(user='Facundo')
    except Study.DoesNotExist:
        return  # If the user "Facundo" does not exist, so we can't associate the records

    # Associate all the previous study records with the user "Facundo"
    study.update(user=facundo_user)

class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_study_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="study",
            options={"ordering": ["date"]},
        ), 
        migrations.RunPython(associate_study_records_with_user),
    ]
